### ISSUE TITLE
Local Blast gives 500 server error

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#366]
Hi Carlos,

Local BLAST gives a 500 server error both when clicking on the icons in Sequence Information and when trying to BLAST new sequence from the menu. NCBI BLAST works fine. Any idea?

Voseq is installed locally using the quick and easy install on a Macbook Pro with OSX 10.11.6. Same issue occurs in both Safari and Firefox.

Marianne

**Comment by vatese** [comment]
That also happens here:

http://try.voseq.com/

**Comment by carlosp420** [comment]
I think it might happen when there the only sequences in the genecode only have question marks, those are removed and there is not much to create the BLAST database.
In any case this should avoid issuing error 500 and notify the user somehow that cannot do the blast.
will look into it.

**Comment by carlosp420** [comment]
This has been fixed in version 2.1.1

please update inside your vagrant environment using the latest commit.

**Comment by mariespe** [comment]
I pulled in the changes, but when I then enter voseq and do 'make migrations' I'm told that no changes where detected and consequently the error persists. 

I don't have sequences with question-marks only, so that can't be the reason for the error. The error happens with all genes in the database.

**Comment by carlosp420** [comment]
Well the changes were not done to the database models, so it is expected to
get the "no changes detected".

To enforce the changes,

enter "vagrant ssh"
type "sudo supervisorctl restart voseq"

see if that helps. If doesn't we will need to investigar further.
I would need a way to reproduce the problem.

El 28 ago. 2017 2:28 AM, "mariespe" <notifications@github.com> escribió:

I pulled in the changes, but when I then enter voseq and do 'make
migrations' I'm told that no changes where detected and consequently the
error persists.

I don't have sequences with question-marks only, so that can't be the
reason for the error. The error happens with all genes in the database.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/VoSeq/VoSeq/issues/366#issuecomment-325280736>, or mute
the thread

**Comment by mariespe** [comment]
I already did that, but the problem is still there.

**Comment by carlosp420** [comment]
It was necessary to install ncbi-blast+ in the vagrant installation. Added fix in version v2.1.3

**Comment by vatese** [comment]
I had BLAST+ installed previously as the nginx log said it was looking for it. Version 2.1.1 fixed the BLAST search error 500 in my case. My suggestion is to add BLAST+ in the documentation as a requirement.
